<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>..\clock.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Fonts\DSEG7ClassicMini-Regular.ttf" />
    <Resource Include="Fonts\d7_mono.ttf" />
  </ItemGroup>
</Project>
